titles = [
    "偽造git提交時間 | Fred's Blog",
    "zsh zle - zsh preexec command modification - Stack Overflow",
    "Micro: Making File Editing Easier in Linux Terminal",
    "[年终总结]一年更新100期！这一年我们是怎么做视频的？_哔哩哔哩_bilibili",
    "Running Debian Linux on Android device natively | by The Quantified VC | Medium",
    "Go 語言課程 - 小惡魔 - AppleBOY",
    "Understanding SSH workflow. Telnet is used to communicate with a… | by Mudit Maheshwari | Medium",
    "How Does SSH Work? {Detailed Overview} | pNAP KB",
    "私有雲軟體的介紹與比較",
    "臺中資網中心IPv6檢測",
    "DAW",
    "Download Full Version of MT Power Drum Kit for free",
    "如何在Linux REAPER里显示中文 - 啦哆咪",
    "VST Plugins, Audio Units, AAX, Instruments and Effects - KVR Audio Software",
    "Bossa Nova Drum Style - Latin Drum Set Beats- Drum Set Tips",
    "How do I configure my linux system to allow JACK to use realtime scheduling? | JACK Audio Connection Kit",
    "來用 Linux 和自由軟體做音樂吧！",
    "Music resources - HackMD",
    "Linchpins Jitsi",
    "行事曆",
    "檔案 - Wancat Cloud",
    "日曆 - Wancat Cloud",
    "Proxmox LAN",
    "Invidious",
    "巴哈姆特動畫瘋",
    "前言 | 新生",
    "Osmosis",
    "Messenger",
    "Matters",
    "ProtonMail",
    "GitHub",
    "HackMD",
    "Jitsi Meet",
    "Cambridge Dictionary | English Dictionary and Thesaurus",
    "Cloudflare - Web Performance & Security",
    "Proxmox",
    "OpenStreetMap",
    "[進擊的巨人】你以為最終卷只加了八頁嗎? 實際上加了三十幾頁的內容(上) - Yusyuu",
    "Dashboard - MINEXMR",
    "REAPER | Videos",
    "https://jisho.org",
    "Monero (XMR) Mining Pool - Monerod",
    "臺北科大校園入口網站",
    "Loudness Penalty: Analyzer",
    "Podcasts | SoundOn Hosting Platform",
    "Recently added videos - Wiwi.Video 好和弦聯播網",
    "鍵盤測試 Keyboard Test",
    "Wancat Gitea",
    "The 'Mixing Secrets' Free Multitrack Download Library",
]
